projects:
  glintapp:
    schemaPath: amplify/backend/api/glintapp/build/schema.graphql
    includes:
      - app/graphql/**/*
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: app/API.ts
        docsFilePath: app/graphql
        region: us-east-2
        apiId: null
        maxDepth: 2
